### ISSUE TITLE
Fulcrum redirects non-SSL API requests

### ISSUE THREAD

**Issue by rvanbaalen** [neverwoods/fulcrum#1]
This results in faulty responses (json_decode trying to parse redirect responses).

Solution: point API request towards https, pull request on the way.

**Comment by flangfeldt** [comment]
So they finally moved to https. Awesome!

**Comment by rvanbaalen** [comment]
Without prior notice.... so UBOSS was down in the meanwhile.

**Comment by flangfeldt** [comment]
Interestingly the URL has the https scheme in all documentation references...
